### ISSUE TITLE
Install error on debian 11 : FileNotFound

### ISSUE THREAD

**Issue by quenenni** [kobotoolbox/kobo-install#229]
**Description**

Installation error when installing on a new debian 11 server

**Steps to Reproduce**

- Create a fresh debian 11 virtual machine.
- install git
- cd /opt
- git clone kobo-install
- cd /opt/kobo-install
- python3 run.py

```
.. all the questions were answered..
Then:

Clonage dans '/opt/kobo-docker'...
remote: Enumerating objects: 4303, done.   
remote: Counting objects: 100% (599/599), done.
remote: Compressing objects: 100% (310/310), done.
remote: Total 4303 (delta 344), reused 500 (delta 287), pack-reused 3704
Réception d'objets: 100% (4303/4303), 2.47 Mio | 6.60 Mio/s, fait.
Résolution des deltas: 100% (2682/2682), fait.
Note : basculement sur '2.023.12b'.

Vous êtes dans l'état « HEAD détachée ». Vous pouvez visiter, faire des modifications
expérimentales et les valider. Il vous suffit de faire un autre basculement pour
abandonner les commits que vous faites dans cet état sans impacter les autres branches

Si vous voulez créer une nouvelle branche pour conserver les commits que vous créez,
il vous suffit d'utiliser l'option -c de la commande switch comme ceci :

  git switch -c <nom-de-la-nouvelle-branche>

Ou annuler cette opération avec :

  git switch -

Désactivez ce conseil en renseignant la variable de configuration advice.detachedHead à false

HEAD est maintenant sur 68be599 Upgrade KPI to 2.023.12b
astuce: Tirer sans spécifier comment réconcilier les branches divergentes
astuce: est découragé. Vous pouvez éliminer ce message en lançant une des
astuce: commandes suivantes avant votre prochain tirage :
astuce: 
astuce:   git config pull.rebase false  # fusion (stratégie par défaut)
astuce:   git config pull.rebase true   # rebasage
astuce:   git config pull.ff only       # avance rapide seulement
astuce: 
astuce: Vous pouvez remplacer "git config" par "git config --global" pour que
astuce: ce soit l'option par défaut pour tous les dépôts. Vous pouvez aussi
astuce: passer --rebase, --no-rebase ou --ff-only sur la ligne de commande pour
astuce: remplacer à l'invocation la valeur par défaut configurée.
Depuis https://github.com/kobotoolbox/kobo-docker
 * tag               2.023.12b  -> FETCH_HEAD
Traceback (most recent call last):
  File "/opt/kobo-install/run.py", line 115, in <module>
    run()
  File "/opt/kobo-install/run.py", line 52, in run
    Command.start(force_setup=force_setup)
  File "/opt/kobo-install/helpers/command.py", line 300, in start
    cls.stop(output=False, frontend_only=frontend_only)
  File "/opt/kobo-install/helpers/command.py", line 414, in stop
    cls.stop_containers('maintenance')
  File "/opt/kobo-install/helpers/command.py", line 489, in stop_containers
    CLI.run_command(command, path)
  File "/opt/kobo-install/helpers/cli.py", line 154, in run_command
    stdout = subprocess.check_output(command,
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
```

**Comment by quenenni** [comment]
I'm adding all the questions and answers I had during the install process:
```
Where do you want to install?
[/opt/kobo-docker]:
Please confirm path [/opt/kobo-docker]
        1) Yes
        2) No
[1]:
Do you want to see advanced options?
        1) Yes
        2) No
[2]: 1
What kind of installation do you need?
        1) On your workstation
        2) On a server
[2]:
Please choose which network interface you want to use?
        eth0) 192.168.2.4
        other) Other
[eth0]:
Do you want to use separate servers for front end and back end?
        1) Yes
        2) No
[2]:
Public domain name? [kobo.local]: kobo.xxxx.org
KPI sub domain? [kf]: kf.kobo.xxxx.org
KoBoCat sub domain? [kc]: kc.kobo.xxxx.org
Enketo Express sub domain name? [ee]: ee.kobo.xxxx.org
Do you want to use HTTPS?
        1) Yes
        2) No
[1]: 2
Are kobo-docker containers behind a reverse-proxy/load-balancer?
        1) Yes
        2) No
[1]: 2
SMTP server? []: localhost
SMTP port? [25]:
SMTP user? []:
From email address? [support@kobo.xxxx.org]:
Super user's username? [super_admin]: admin
Super user's password? [mtxauzHoYyookotMuJy2]: yyyyyyy
Docker Compose prefix? (leave empty for default) []:
Use staging mode?
        1) Yes
        2) No
[2]:
KoBoCat PostgreSQL database name?
[kobocat]:
KPI PostgreSQL database name?
[koboform]:
PostgreSQL user's username?
[kobo]:
PostgreSQL user's password?
[2A5qSxqmWzLaL3cTNP7z]:
Do you want to tweak PostgreSQL settings?
        1) Yes
        2) No
[2]:
MongoDB root's username?
[root]:
MongoDB root's password?
[LzFOT99eRt3ULSh7b821]:
MongoDB user's username?
[kobo]:
MongoDB user's password?
[gH4zhFyuXsYKiPzab2Oi]:
Do you want to run the Redis containers from this server?
        1) Yes
        2) No
[1]:
Redis password?
[vPZiC8s57tm5wKOA1Gwk]:
Max memory (MB) for Redis cache container?
Leave empty for no limits
[]:
Do you want to expose back-end container ports (`PostgreSQL`, `MongoDB`, `Redis`)?
        1) Yes
        2) No
[2]:
Do you want to customize the application secret keys?
        1) Yes
        2) No
[2]:
Do you want to use AWS S3 storage?
        1) Yes
        2) No
[2]:
Google Analytics Identifier []:
Google API Key []:
Do you want to use Sentry?
        1) Yes
        2) No
[2]:
Do you want to tweak uWSGI settings?
        1) Yes
        2) No
[2]:
Do you want to restrict API calls between KPI and KoBoCAT to their internal domain names?
        1) Yes
        2) No
[1]:
Length of users' session (in hours)?
[168]:
Do you want to add additional settings to the front-end docker containers?
        1) Yes
        2) No
[2]:
Do you want to add additional settings to the back-end docker containers?
        1) Yes
        2) No
[2]:
Do you want to activate backups?
        1) Yes
        2) No
[2]: 1
```

**Comment by quenenni** [comment]
Docker must be installed manually before running the script..
