### ISSUE TITLE
Error during installation : OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by shivabhusal** [kobotoolbox/kobo-install#27]
MacOS: 10.14.5 Beta (18F131a)

```python
Cloning into '/Users/john/projects/kobo-install/kobo-docker'...
remote: Enumerating objects: 70, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 2823 (delta 33), reused 38 (delta 17), pack-reused 2753
Receiving objects: 100% (2823/2823), 2.08 MiB | 562.00 KiB/s, done.
Resolving deltas: 100% (1725/1725), done.
Already on 'master'
From https://github.com/kobotoolbox/kobo-docker
 * branch            master     -> FETCH_HEAD
Traceback (most recent call last):
  File "run.py", line 50, in <module>
    run(force_setup=True)
  File "run.py", line 36, in run
    Command.start()
  File "/Users/john/projects/kobo-install/helpers/command.py", line 217, in start
    cls.stop(output=False, frontend_only=frontend_only)
  File "/Users/john/projects/kobo-install/helpers/command.py", line 311, in stop
    CLI.run_command(backend_command, config.get("kobodocker_path"))
  File "/Users/john/projects/kobo-install/helpers/cli.py", line 88, in run_command
    stdout = subprocess.check_output(command, universal_newlines=True, cwd=cwd)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by jnm** [comment]
Do you have `docker-compose` installed?

**Comment by noliveleger** [comment]
Ticket closed due to inactivity. Please visit https://community.kobotoolbox.org/c/kobo-install for help.
